Kirilushkin Aleksandr Tasks 1-10
KirilushkinAleksandr/ui-internship-lwo2 pull request #1
Opened 2019-09-10 09:58 UTC by KirilushkinAleksandr

2019-09-10 10:13 UTC, alexkond requested changes

2019-09-10 10:13 UTC, alexkond commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +  let tempArr = str.split(' ');
Consider using `string.replace()` method

2019-09-10 10:13 UTC, alexkond commented on tasks/3_is-boolean/is-boolean.js
> +  if (typeof(value) === 'boolean') {
`typeof(value) === 'boolean'` itself returns `boolean`.
This is a bad practice:
``` javascript
if(true){
 return true;
} else {
 return false;
}```

2019-09-10 10:13 UTC, alexkond commented on tasks/5_profile-lookup/profile-lookup.js
> +          return item[prop];
Could be simplified to 
``` javascript
if (key !== 'firstName') {
 return item[prop];
}
```

2019-09-10 10:13 UTC, alexkond commented on tasks/9_find-numbers/find-numbers.js
> +    digitsArr[index] = +digitsArr[index];
Please use `Number(val)` to cast a value to a number, it clearly shows your intent

2019-09-10 10:13 UTC, alexkond commented on tasks/7_random-fraction/random-fraction.js
> +  return +Math.random().toFixed(1);
Please use `Number(val)` to cast a value to a number, it clearly shows your intent, and isn't

2019-09-10 11:10 UTC, akimovaa submitted a review, later dismissed

2019-09-10 11:52 UTC, alexkond submitted a review, later dismissed

2019-09-10 11:52 UTC, alexkond commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +  return str.replace(/ /g, '');
Use `\s` symbol to match spaces in regex

2019-09-10 14:20 UTC, vovcyan submitted a review, later dismissed

2019-09-10 14:20 UTC, vovcyan commented on tasks/1_golf-score/golf-score.js
> +let GOLF_SCORES = {
const

2019-09-10 14:30 UTC, KalachevDev submitted a review, later dismissed

2019-09-10 14:30 UTC, KalachevDev commented on tasks/1_golf-score/golf-score.js
> +let GOLF_SCORES = {
const

2019-09-10 17:30 UTC, alexkond approved these changes

2019-09-11 05:54 UTC, vovcyan approved these changes

2019-09-11 07:50 UTC, savchukm approved these changes

2019-09-11 09:11 UTC, merged