Kirilushkin Aleksandr Tasks 51-60
KirilushkinAleksandr/ui-internship-lwo2 pull request #6
Opened 2019-09-17 10:02 UTC by KirilushkinAleksandr

2019-09-19 04:44 UTC, savchukm requested changes

2019-09-19 04:44 UTC, savchukm commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +function returnRomanNum(num, step) {
`getRomanNum` is better name for function

2019-09-19 04:44 UTC, savchukm commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +    num = 1;
This code block unachievable

2019-09-19 04:44 UTC, savchukm commented on tasks/55_find-object-analogy/find-object-analogy.js
> +  arr.forEach((Obj) => {
Variable should have lower case first letter

2019-09-19 04:47 UTC, savchukm commented on tasks/51_abbreviated-name/abbreviated-name.js
> +function abbreviated(name) {
Please jsdoc for every function

2019-09-19 05:30 UTC, alexkond requested changes

2019-09-19 05:30 UTC, alexkond commented on tasks/58_missed-letters/missed-letters.js
> +  const lets = str.split('');
Why you save letters? Are you afraid to run out of them? `letters` is a much better readable name.

2019-09-20 13:26 UTC, alexkond submitted a review, later dismissed

2019-09-20 15:34 UTC, KalachevDev submitted a review, later dismissed

2019-09-25 13:13 UTC, alexkond approved these changes

2019-09-25 13:48 UTC, akimovaa approved these changes

2019-09-25 14:28 UTC, merged