Kirilushkin Aleksandr Tasks 61-70
KirilushkinAleksandr/ui-internship-lwo2 pull request #7
Opened 2019-09-18 12:26 UTC by KirilushkinAleksandr

2019-09-24 04:56 UTC, alexkond requested changes

2019-09-24 04:56 UTC, alexkond commented on tasks/61_spinal-case/spinal-case.js
> +  const arr = str.split('');
You're changing every value of array so it looks like it is a case for `.map()` method.

2019-09-24 04:56 UTC, alexkond commented on tasks/62_swap-cases/swap-cases.js
> +      function(item) {
Consider using arrow function

2019-09-24 04:56 UTC, alexkond commented on tasks/65_smaller-common-multiple/smaller-common-multiple.js
> +    let start = arr[0] < arr[1] ? arr[0] : arr[1];
Consider using `Math.max()` here

2019-09-24 04:56 UTC, alexkond commented on tasks/67_find-elements/find-elements.js
> +  const resIndex = arr.findIndex(func);
I think the idea of this task is to write this method yourself, not to create a wrapper.

2019-09-25 18:31 UTC, vovcyan submitted a review, later dismissed

2019-09-25 18:31 UTC, vovcyan commented on tasks/65_smaller-common-multiple/smaller-common-multiple.js
> +  let finish = Math.max(arr[0], arr[1]);
const

2019-09-26 05:57 UTC, alexkond approved these changes

2019-09-26 06:17 UTC, savchukm approved these changes

2019-09-26 06:27 UTC, merged