Kirilushkin Aleksandr Tasks 71-80
KirilushkinAleksandr/ui-internship-lwo2 pull request #8
Opened 2019-09-19 19:46 UTC by KirilushkinAleksandr

2019-09-24 05:18 UTC, alexkond requested changes

2019-09-24 05:18 UTC, alexkond commented on tasks/71_binary-encode/binary-encode.js
> +  }
`});` should be on the same line

2019-09-25 18:33 UTC, alexkond submitted a review, later dismissed

2019-09-25 18:35 UTC, vovcyan requested changes

2019-09-25 18:35 UTC, vovcyan commented on tasks/72_carrying/carrying.js
> +  if (typeof(input[0]) !== 'number' ) {
(typeof(input[0]) !== 'number')

2019-09-25 18:35 UTC, vovcyan commented on tasks/72_carrying/carrying.js
> +      if (typeof(input) !== 'number' ) {
Same

2019-09-25 18:35 UTC, vovcyan commented on tasks/72_carrying/carrying.js
> +  if (typeof(input[1]) !== 'number' ) {
Same

2019-09-25 18:35 UTC, vovcyan commented on tasks/76_deep-object-clone/deep-object-clone.js
> +    } else clone[key] = inputObj[key];
{
 clone[key] = inputObj[key];
}

2019-09-25 18:35 UTC, vovcyan commented on tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
> +    if (count === 0) {
!count

2019-09-25 18:35 UTC, vovcyan commented on tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
> +      0
Weird formatting

2019-09-26 08:35 UTC, vovcyan approved these changes

2019-09-26 09:20 UTC, alexkond approved these changes

2019-09-26 09:30 UTC, merged