Kirilushkin Aleksandr Tasks 81-90
KirilushkinAleksandr/ui-internship-lwo2 pull request #9
Opened 2019-09-22 20:26 UTC by KirilushkinAleksandr

2019-09-23 06:55 UTC, vovcyan requested changes

2019-09-23 06:55 UTC, vovcyan commented on tasks/81_buying-car/buying-car.js
> +function nbMonths(
JSDoc

2019-09-25 18:39 UTC, alexkond requested changes

2019-09-25 18:39 UTC, alexkond commented on tasks/83_missing-term/missing-term.js
> +    if (input[i-1] + step !== input[i]) {
Spaces around mathematical operand

2019-09-25 18:39 UTC, alexkond commented on tasks/88_record-collection/record-collection.js
> +      } else collection[id][prop].push(value);
Please add braces for else blocks, that way code will be more readable

2019-09-26 06:01 UTC, alexkond approved these changes

2019-09-26 06:20 UTC, savchukm approved these changes

2019-09-26 06:27 UTC, merged